export const ROUTES = {
  LOGIN: 'Login',
  DASHBOARD: 'Dashboard',
  LOTS: 'Lots',
  LOT_DETAIL: 'LotDetail',
  CERTIFY: 'Certify',
  REGULATOR: 'Regulator',
  REGULATOR_DASHBOARD: 'RegulatorDashboard',
  REGULATOR_ANALYSIS: 'RegulatorAnalysis',
  REGULATOR_ALERTS: 'RegulatorAlerts',
  REGULATOR_LOTS: 'RegulatorLots',
  PRODUCER: 'Producer',
  PRODUCER_MENU: 'ProducerMenu',
  TRANSPORTER_MENU: 'TransporterMenu',
  TRANSPORTER_SCANNER: 'TransporterScanner',
  ADMIN_MENU: 'AdminMenu',
  TRANSACTIONS: 'Transactions',
};
